---
title: "Instruções para o planejamento de experimentos"
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

## 1. Reconhecimento e caracterização do problema

Reconhecer algum processo que necessite de experimentação e desenvolver
todas as ideias sobre os objetivos do problema. É importante usar todo o
conhecimento já existente sobre o problema. Por esse motivo, uma
**abordagem de grupo** deve ser adotada. É útil preparar uma lista com
problemas e perguntas específicas que poderão ser respondidas pelo
experimento. Existem muitos objetivos para se realizar um experimento,
mas os principais são:

- Caracterização (para processos novos)
- Otimização (níveis ótimos de funcionamento)
- Confirmação (se funciona como no passado ou alguma teoria)
- Descoberta (novos materiais ou abordagens)
- Estabilidade (em quais condições o sistema degrada?)

Considerar ao invés de um grande experimento muito compreensivo, uma
**abordagem sequencial**, ou seja, uma série de experimentos menores.

## 2. Escolha da variável resposta

- Certificar que a variável resposta é de fato relevante para responder
  as perguntas do problema.
- Pode haver mais de uma.
- Verificar de que forma, e com qual precisão ela será medida.

## 3. Escolha de fatores, níveis e amplitude

Fatores podem ser classificados como **fatores do desenho** e **fatores
nuisance** (acessórios, secundários, de segunda ordem, ...).

Os fatores do desenho são aqueles que o experimentador tem o interesse
em variar. Podem ser classificados em:

- **Fatores do desenho**: aqueles realmente de interesse e selecionados para
  o experimento.
- **Fatores mantidos constantes**: aqueles que podem influenciar na
  resposta, mas que não há interesse para o experimento específico, e
  será mantido à um nível específico.
- **Fatores em que se permite variar**: pequenas variações de material, por
  exemplo, podem ser permitidas. A casualização é fundamental para se
  anular essas pequanas variações.

Geralmente se assume que os fatores mantidos constantes e aqueles em que
se permite variar possuem efeitos relativamente pequenos.

Fatores *nuisance*, no entanto, podem ter efeitos grandes na resposta,
mas também não se tem interesse neles no experimento atual. Podem ser:

- **Controláveis** (entram no modelo, como blocos por exemplo)
- **Não controláveis** (se puderem ser medidos podem entrar no modelo)
- **Ruídos** (varia e não pode ser controlado)

Após definir os fatores, é necessário selecionar o número de níveis
(à princípio vamos usar 2) e a amplitude de variação entre eles. Se o
objetivo for caracterização, por exemplo, as amplitudes devem ser
grandes.

## 4. Escolha do desenho experimental

Escolha do tamanho da amostra (número de réplicas), a seleção da ordem
de execução, e se haverá blocagem.

## 5. Execução do experimento

Controlar o processo como planejado. Geralmente é recomendado realizar
algum (ou alguns) **experimentos piloto**, para se ter uma ideia do erro
experimental, e se serão necessários ajustes no experimento.

## 6. Análise dos dados

Se o planejamento e execução foram bem feitos, a análise já estará
pré-determinada. Deve-se utilizar métodos gráficos, fazer a seleção de
modelos, analisar resíduos e re-analisar se necessário.

## 7. Conclusões e recomendações

Após o experimento, o experimentador deve descrever conclusões
**práticas** baseadas nos resultados, e ainda recomendar estudos
posteriores, com os ajustes que descobriu-se ser necessário.

Note que todo esse processo é **iterativo**!

Os passos 1-3 são chamados de **planejamento pré-experimental**, e são
fundamentais para o bom desenvolvimento de um experimento. Por isso,
vamos usar este guia para facilitar essa fase:

1. Objetivos do experimento
2. Conhecimento relevante sobre o problema
3. Listar:
     - variável resposta
     - os níveis normais de operação dessa variável
     - os níveis que podem ser de fato medidos
4. Listar: fatores controláveis
5. Listar: fatores que serão considerados fixos
6. Listar: fatores *nuisance*
7. Listar: possíveis interações
8. Listar: restrições do experimento (aquisição de dados, material, etc)
9. Desenho experimental inicial
10. Propor a análise e técnicas de representação dos resultados e do
    experimento
11. Experimento piloto deverá ser conduzido? Sim/não. Por que?

O guia completo está disponível em:
[guia-planejamento.html](misc/guia-planejamento.html), e o código fonte
está em [guia-planejamento.Rmd](misc/guia-planejamento.Rmd).
